### PR TITLE
remove peer dep

### PR DESCRIPTION
**Pull request by kristianmandrup**
Was causing conflict

### CODE REVIEW

**Comment by ta2edchimp** [comment]
I don't think, that removing `inquirer` as a peer dependency (or moving it to just the dev dependencies) would the be the right thing to do.
As I see this is coming from the issue you reported in #6 you were reporting, I assume you get the conflict while having a newer version of `inquirer` installed?

**Comment by ta2edchimp** [comment]
Ok, I think I get.
You want to use it with an alternative to the original `inquirer` module, i guess?
If it is so, would you mind updating the README's first line to list the alternative(s) it's working with, too?
I'd happily merge and publish afterwards.

**Comment by kristianmandrup** [comment]
I'm using it with `inquirer-shortcuts`

**Comment by kristianmandrup** [comment]
Great! Thanks :)

I'm using it in my new [master-inquisitor](https://www.npmjs.com/package/master-inquisitor) lib

**Pull request merged**
